version: '3'
services:
  app:
    container_name: linkedin
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - api
  api:
    container_name: api
    restart: always
    build: ./linkedin-api
    ports:
      - '3001:3001'
    links:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
volumes:
  esdata: